export {
    ACTIVE_THREADS_PER_GUILD,
    CHANNELS_PER_GUILD,
    CHOICES_PER_AUTOCOMPLETE,
    EMBED_COMBINED_LENGTH,
    EMBED_DESCRIPTION_LENGTH,
    EMBED_FIELD_NAME_LENGTH,
    EMBED_FOOTER_LENGTH,
    EMBED_TITLE_LENGTH,
    EMBEDS_PER_MESSAGE,
    FIELDS_PER_EMBED,
    GUILDS_PER_SHARD,
    PINS_PER_CHANNEL,
    ROLES_PER_GUILD
} from './discord-limits';
